In [1]:
pip install mysql-connector-python

Collecting mysql-connector-python
  Downloading mysql_connector_python-8.0.26-cp38-cp38-win_amd64.whl (799 kB)
Requirement already satisfied: protobuf>=3.0.0 in c:\users\admin\appdata\roaming\python\python38\site-packages (from mysql-connector-python) (3.15.8)
Requirement already satisfied: six>=1.9 in c:\users\admin\appdata\roaming\python\python38\site-packages (from protobuf>=3.0.0->mysql-connector-python) (1.15.0)
Installing collected packages: mysql-connector-python
Successfully installed mysql-connector-python-8.0.26
Note: you may need to restart the kernel to use updated packages.

In [4]:
#Importing required packages
import mysql.connector
from getpass import getpass
from mysql.connector import connect, Error
#Function to connect to the server
def create_server_connection(host_name, user_name, user_password):
    connection = None
    try:
        connection = mysql.connector.connect(
            host=host_name,
            user=user_name,
            passwd=user_password,
        )
        print("MySQL Database connection successful")
    except Error as err:
        print(f"Error: '{err}'")

    return connection

In [5]:
# Establishin a connection
connection = create_server_connection("Mysql@localhost:3306", "root", "Root@123")

Error: '2003: Can't connect to MySQL server on '%-.100s:%u' (%s) (Warning: %u format: a number is required, not str)'

In [4]:
# Function to create a database
def create_database(connection, query):
    cursor = connection.cursor()
    try:
        cursor.execute(query)
        print("Database created successfully")
    except Error as err:
        print(f"Error: '{err}'")

In [5]:
# Cresting a database named "mydb"
query = "CREATE DATABASE mydb"
create_database(connection, query)

Error: '1007 (HY000): Can't create database 'mydb'; database exists'

In [6]:
# Function to connect to the database
def create_db_connection(host_name, user_name, user_password, db_name):
    connection = None
    try:
        connection = mysql.connector.connect(
            host=host_name,
            user=user_name,
            passwd=user_password,
            database=db_name
        )
        print("MySQL Database connection successful")
    except Error as err:
        print(f"Error: '{err}'")

    return connection

# Function to execute a query
def execute_query(connection, query):
    cursor = connection.cursor()
    try:
        cursor.execute(query)
        connection.commit()
        print("Query successful")
    except Error as err:
        print(f"Error: '{err}'")

In [6]:
 # Importing csv files to be converted into sql tables
import pandas as pd
df = pd.read_csv('MCQ_Dataset1.csv')

# Creating questions TABLE

In [7]:
try:
    conn = mysql.connector.connect(host='localhost', database='mydb', user='root', password='Root@123')
    if conn.is_connected():
        cursor = conn.cursor()
        cursor.execute("select database();")
        record = cursor.fetchone()
        print("You're connected to database: ", record)
        cursor.execute('DROP TABLE IF EXISTS questions;')
        print('Creating table....')
#  creating table named questions
        cursor.execute("CREATE TABLE questions(qno int,question varchar(512),correct varchar(255),A varchar(255),B varchar(255),C varchar(255),D varchar(255),Concept int,Difficulty int)")
        print("Table is created....")
        #loop through the data frame
        for i,row in df.iterrows():
            #here %S means string values 
            sql = "INSERT INTO mydb.questions VALUES (%s,%s,%s,%s,%s,%s,%s,%s,%s)"
            cursor.execute(sql, tuple(row))
            print("Record inserted")
            # the connection is not auto committed by default, so we must commit to save our changes
            conn.commit()
except Error as e:
            print("Error while connecting to MySQL", e)

You're connected to database:  ('mydb',)
Creating table....
Table is created....
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted

# Creating responses TABLE

In [11]:
try:
    conn = mysql.connector.connect(host='localhost', database='mydb', user='root', password='Root@123')
    if conn.is_connected():
        cursor = conn.cursor()
        cursor.execute("select database();")
        record = cursor.fetchone()
        print("You're connected to database: ", record)
        cursor.execute('DROP TABLE IF EXISTS responses;')
        print('Creating table....')
# creating table named responses
        cursor.execute("CREATE TABLE responses(q1 int, q2 int, q3 int, q4 int, q5 int)")
        print("Table is created....")
        Delete_all_rows = """truncate table responses """
        cursor.execute(Delete_all_rows)
        connection.commit()
        print("All Record Deleted successfully ")
        print(cursor.rowcount, " Record Deleted successfully")
        
except Error as e:
            print("Error while connecting to MySQL", e)

You're connected to database:  ('mydb',)
Creating table....
Table is created....
All Record Deleted successfully
0  Record Deleted successfully

In [13]:
try:
    conn = mysql.connector.connect(host='localhost', database='mydb', user='root', password='Root@123')
    if conn.is_connected():
        cursor = conn.cursor()
        cursor.execute("select database();")
        record = cursor.fetchone()
        print("You're connected to database: ", record)
        cursor.execute('DROP TABLE IF EXISTS difficulties;')
        print('Creating table....')
# creating table named responses
        cursor.execute("CREATE TABLE difficulties(q1 int, q2 int, q3 int, q4 int, q5 int)")
        print("Table is created....")
                
except Error as e:
            print("Error while connecting to MySQL", e)

You're connected to database:  ('mydb',)
Creating table....
Table is created....

In [14]:
try:
    conn = mysql.connector.connect(host='localhost', database='mydb', user='root', password='Root@123')
    if conn.is_connected():
        cursor = conn.cursor()
        cursor.execute("select database();")
        record = cursor.fetchone()
        print("You're connected to database: ", record)
        cursor.execute('DROP TABLE IF EXISTS qnos;')
        print('Creating table....')
# creating table named responses
        cursor.execute("CREATE TABLE qnos(q1 int, q2 int, q3 int, q4 int, q5 int)")
        print("Table is created....")
                
except Error as e:
            print("Error while connecting to MySQL", e)

You're connected to database:  ('mydb',)
Creating table....
Table is created....